name: Test Windows
on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  test:
    name: Test Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        erlang_version:
        #! - "23"
        - "24"
    timeout-minutes: 120
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v3
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1.11
      with:
        otp-version: ${{ matrix.erlang_version }}
        elixir-version: 1.12.3
    #! - name: MOUNT BAZEL CACHE
    #!   uses: actions/cache@v1
    #!   with:
    #!     path: "/home/runner/repo-cache/"
    #!     key: repo-cache
    - name: CONFIGURE BAZEL
      shell: bash
      run: |
        ERL_PATH="$(which erl)"
        IEX_PATH="$(which iex)"
        sed -i"_orig" 's/build --experimental_enable_bzlmod//' .bazelrc
        cat << EOF >> user.bazelrc
          startup --output_user_root=C:/tmp
          startup --windows_enable_symlinks
          build --enable_runfiles

          build:buildbuddy --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}

          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PUBLIC
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-windows-${{ matrix.erlang_version }}
          # build:buildbuddy --repository_cache=/home/runner/repo-cache/
          build:buildbuddy --color=yes
          build:buildbuddy --disk_cache=

          build --@rules_erlang//:erlang_version=${{ matrix.erlang_version }}
          build --@rules_erlang//:erlang_home="${ERL_PATH/\/bin\/erl/}"
          build --//:elixir_home="${IEX_PATH/\/bin\/iex/}"

          build --extra_toolchains=@rules_erlang//tools:erlang_external_toolchain
          build --extra_toolchains=//bazel/elixir:elixir_external_toolchain
        EOF

        bazelisk info release
    - name: RUN TESTS
      shell: cmd
      run: |
        bazelisk test //... ^
          --config=buildbuddy ^
          --test_tag_filters=-aws,-bats,-starts-background-broker ^
          --build_tests_only ^
          --verbose_failures
